version: '3'

services:
  web:
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/webdir
    ports:
        - '8080:8000'
    env_file:
      - .env
